name: dev_pr

on:
  workflow_call:
    secrets:
      PAT_TOKEN:
        required: true


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  get-workflow-type:
    runs-on: ubuntu-latest
    outputs:
      workflow_type: ${{ steps.get-workflow.outputs.workflow_type }}
    steps:
      - name: Get workflow type from pyproject.toml
        id: get-workflow
        uses: j-moralejo-pinas/ci-cd-python/.github/actions/get-workflow-type@main
  format:
    name: format
    runs-on: ubuntu-latest
    needs: get-workflow-type
    outputs:
      did_push: ${{ steps.format.outputs.did_push || 'false' }}
    steps:
      - name: Run format action
        id: format
        uses: j-moralejo-pinas/ci-cd-python-gitflow/.github/actions/format@main
        with:
          pat_token: ${{ secrets.PAT_TOKEN }}

  test:
    name: test
    runs-on: ubuntu-latest
    needs: [get-workflow-type, format]
    if: needs.format.outputs.did_push != 'true'
    steps:
      - name: Run test action
        uses: j-moralejo-pinas/ci-cd-python-gitflow/.github/actions/test@main
