name: dev_pr

on:
  workflow_call:
    secrets:
      PAT_TOKEN:
        required: true


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-up-to-date:
    name: check-up-to-date
    runs-on: ubuntu-latest
    steps:
      - name: Verify branch is up to date
        uses: j-moralejo-pinas/ci-cd-python/actions/check-up-to-date@main
        with:
          target_branch: "dev"
          ignore_patterns: "hotfix/*,main"

  format:
    name: format
    runs-on: ubuntu-latest
    needs: check-up-to-date
    outputs:
      did_push: ${{ steps.format.outputs.did_push || 'false' }}
    steps:
      - name: Run format action
        id: format
        uses: j-moralejo-pinas/ci-cd-python/actions/format@main
        with:
          pat_token: ${{ secrets.PAT_TOKEN }}

  test:
    name: test
    runs-on: ubuntu-latest
    needs: format
    if: needs.format.outputs.did_push != 'true'
    steps:
      - name: Run test action
        uses: j-moralejo-pinas/ci-cd-python/actions/test@main
