name: main_pr

on:
  workflow_call:
    secrets:
      PAT_TOKEN:
        required: true

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  check-up-to-date:
    name: check-up-to-date
    runs-on: ubuntu-latest
    steps:
      - name: Verify branch is up to date
        uses: j-moralejo-pinas/ci-cd-python/actions/check-up-to-date@main
        with:
          target_branch: "main"
          ignore_patterns: "hotfix/*,main"

  get-workflow-type:
    runs-on: ubuntu-latest
    needs: check-up-to-date
    outputs:
      workflow_type: ${{ steps.get-workflow.outputs.workflow_type }}
    steps:
      - name: Get workflow type from pyproject.toml
        id: get-workflow
        uses: j-moralejo-pinas/ci-cd-python/actions/get-workflow-type@main

  check-source-branch:
    name: check-source-branch
    runs-on: ubuntu-latest
    needs: get-workflow-type
    steps:
      - name: Validate source branch
        uses: j-moralejo-pinas/ci-cd-python/actions/check-source-branch@main
        with:
          allowed_branches: ${{ needs.get-workflow-type.outputs.workflow_type == 'gitflow' && 'dev' || '' }}
          allowed_prefixes: ${{ needs.get-workflow-type.outputs.workflow_type == 'gitflow' && 'hotfix/,release/,meta/,major/' || 'feature/,bugfix/,fix/,hotfix/,release/,meta/,major/' }}

  update-changelog:
    name: update-changelog
    runs-on: ubuntu-latest
    needs: [get-workflow-type, check-source-branch]
    outputs:
      did_push: ${{ steps.update-changelog.outputs.did_push || 'false' }}
    steps:
      - name: Update changelog
        if: startsWith(github.head_ref, 'hotfix/') || startsWith(github.head_ref, 'release/') || startsWith(github.head_ref, 'major/')
        id: update-changelog
        uses: j-moralejo-pinas/ci-cd-python/actions/update-changelog@main
        with:
          workflow_type: ${{ needs.get-workflow-type.outputs.workflow_type }}
          pat_token: ${{ secrets.PAT_TOKEN }}
          gh_token: ${{ github.token }}

  format:
    name: format
    needs: [get-workflow-type, update-changelog]
    if: needs.update-changelog.outputs.did_push != 'true'
    runs-on: ubuntu-latest
    outputs:
      did_push: ${{ steps.format.outputs.did_push || 'false' }}
    steps:
      - name: Run format action
        id: format
        uses: j-moralejo-pinas/ci-cd-python/actions/format@main
        with:
          pat_token: ${{ secrets.PAT_TOKEN }}

  code-quality:
    name: code-quality
    runs-on: ubuntu-latest
    needs: [get-workflow-type, format]
    if: needs.format.outputs.did_push != 'true'
    steps:
      - name: Run code quality action
        uses: j-moralejo-pinas/ci-cd-python/actions/code-quality@main

  test:
    name: test
    runs-on: ubuntu-latest
    needs: [get-workflow-type, code-quality]
    steps:
      - name: Run test action
        uses: j-moralejo-pinas/ci-cd-python/actions/test@main
