name: main_pr

on:
  workflow_call:
    secrets:
      PAT_TOKEN:
        required: true

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  get-workflow-type:
    runs-on: ubuntu-latest
    outputs:
      workflow_type: ${{ steps.get-workflow.outputs.workflow_type }}
    steps:
      - name: Get workflow type from pyproject.toml
        id: get-workflow
        uses: j-moralejo-pinas/ci-cd-python/actions/get-workflow-type@main

  code-quality:
    name: code-quality
    runs-on: ubuntu-latest
    needs: [get-workflow-type]
    continue-on-error: true
    steps:
      - name: Run code quality action
        uses: j-moralejo-pinas/ci-cd-python/actions/code-quality@main

  test:
    name: test
    runs-on: ubuntu-latest
    needs: [get-workflow-type, code-quality]
    steps:
      - name: Run test action
        uses: j-moralejo-pinas/ci-cd-python/actions/test@main
