name: tag_on_merge

on:
  workflow_call:
    secrets:
      PAT_TOKEN:
        required: true

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  get-workflow-type:
    runs-on: ubuntu-latest
    outputs:
      workflow_type: ${{ steps.get-workflow.outputs.workflow_type }}
    steps:
      - name: Get workflow type from pyproject.toml
        id: get-workflow
        uses: j-moralejo-pinas/ci-cd-python/.github/actions/get-workflow-type@main

  semver-tag:
    name: semver-tag
    if: github.event.pull_request.merged == true && !startsWith(github.event.pull_request.head.ref, 'meta')
    runs-on: ubuntu-latest
    needs: get-workflow-type
    steps:
      - name: Run semver tag action
        id: semver
        with:
          pat_token: ${{ secrets.PAT_TOKEN }}
        uses: j-moralejo-pinas/ci-cd-python-gitflow/.github/actions/semver-tag@main
